insert into public.starter_chore_templates (
  slug,
  title,
  emoji,
  description,
  category,
  location,
  frequency,
  estimated_minutes,
  difficulty,
  base_points,
  minimum_age,
  requires_parent_review,
  requires_evidence,
  evidence_type,
  undesirable_score,
  dependency_slugs,
  completion_check_text,
  safety_notes
) values
  (
    'wash-dishes',
    'Wash Dishes',
    ':plate:',
    'Wash, dry, and put away dishes; wipe sink, counters, table, and chairs.',
    'kitchen',
    'Kitchen',
    'daily',
    25,
    3,
    30,
    10,
    true,
    false,
    null,
    1,
    '{}',
    'No dishes left. Sink clean. Counters dry and clutter-free.',
    null
  ),
  (
    'clean-gas-cooker',
    'Clean Gas Cooker',
    ':stove:',
    'Clean grates, burner caps, knobs, cooker surface, hood exterior, and grease buildup.',
    'kitchen',
    'Kitchen',
    'weekly',
    30,
    4,
    45,
    12,
    true,
    true,
    'photo',
    3,
    '{}',
    'No grease on cooker.',
    'Parent should configure whether this is safe for younger children.'
  ),
  (
    'sweep-kitchen',
    'Sweep Kitchen',
    ':broom:',
    'Sweep kitchen and dining floor; take trash, compost, and recycling to configured places.',
    'kitchen',
    'Kitchen',
    'daily',
    15,
    2,
    15,
    8,
    true,
    false,
    null,
    1,
    '{}',
    'No visible crumbs or dirt on floor. Trash cans and recycling container empty.',
    null
  ),
  (
    'mop-kitchen',
    'Mop Kitchen',
    ':mop:',
    'Mop the kitchen after sweeping is complete.',
    'kitchen',
    'Kitchen',
    'weekly',
    20,
    3,
    25,
    10,
    true,
    false,
    null,
    2,
    '{sweep-kitchen}',
    'Floor visibly clean with no sticky spots.',
    null
  ),
  (
    'clean-living-room',
    'Clean Parlour / Living Room',
    ':sofa:',
    'Arrange cushions, fold blankets, remove trash, dust lightly, and vacuum or sweep.',
    'living_area',
    'Living Room',
    'daily',
    20,
    2,
    20,
    8,
    true,
    false,
    null,
    1,
    '{}',
    'Room tidy with no visible clutter.',
    null
  ),
  (
    'clean-guest-half-bathroom',
    'Clean Guest Half Bathroom',
    ':bathroom:',
    'Clean toilet, sink, counter, mirror, hand towel, and floor.',
    'bathroom',
    'Guest Half Bathroom',
    'weekly',
    30,
    4,
    45,
    11,
    true,
    true,
    'photo',
    5,
    '{}',
    'No stains. Smells fresh.',
    null
  ),
  (
    'clean-entry-closet',
    'Clean Entry Closet',
    ':closet:',
    'Arrange shoes, hang coats, and remove trash or unnecessary items.',
    'entryway',
    'Entry Closet',
    'weekly',
    15,
    2,
    15,
    8,
    true,
    false,
    null,
    1,
    '{}',
    'Organized and easy to access.',
    null
  ),
  (
    'clean-front-entryway',
    'Clean Front Entryway',
    ':door:',
    'Sweep floor, arrange shoes and mats, and wipe door handle and surfaces.',
    'entryway',
    'Front Entryway',
    'daily',
    15,
    2,
    15,
    8,
    true,
    false,
    null,
    1,
    '{}',
    'Clean and uncluttered.',
    null
  ),
  (
    'clean-stairs',
    'Clean Stairs',
    ':stairs:',
    'Remove items, sweep or vacuum steps, and wipe handrails.',
    'hallway',
    'Stairs',
    'weekly',
    20,
    3,
    25,
    9,
    true,
    false,
    null,
    2,
    '{}',
    'No debris on steps.',
    'Parent should approve for younger kids.'
  ),
  (
    'clean-upstairs-living-room',
    'Clean Upstairs Living Room',
    ':sofa:',
    'Declutter, arrange furniture and cushions, and vacuum or sweep.',
    'living_area',
    'Upstairs Living Room',
    'weekly',
    20,
    2,
    20,
    8,
    true,
    false,
    null,
    1,
    '{}',
    'Room tidy. Floor clean.',
    null
  ),
  (
    'clean-laundry-room',
    'Clean Laundry Room',
    ':laundry:',
    'Remove lint and trash, wipe machines, sweep or mop floor, and organize supplies.',
    'laundry',
    'Laundry Room',
    'weekly',
    25,
    3,
    30,
    10,
    true,
    false,
    null,
    2,
    '{}',
    'Clean surfaces. Clean floor.',
    null
  ),
  (
    'clean-bathroom-general',
    'Clean Bathroom - General',
    ':bathroom:',
    'Clean toilet, sink, mirror, counters, floor, and trash.',
    'bathroom',
    'Bathroom',
    'weekly',
    30,
    4,
    45,
    11,
    true,
    true,
    'photo',
    5,
    '{}',
    'No stains. Smells clean.',
    null
  ),
  (
    'clean-upstairs-full-bathroom',
    'Clean Upstairs Full Bathroom',
    ':bathtub:',
    'Complete general bathroom tasks and clean tub or shower walls.',
    'bathroom',
    'Upstairs Full Bathroom',
    'weekly',
    40,
    5,
    60,
    12,
    true,
    true,
    'photo',
    5,
    '{clean-bathroom-general}',
    'No soap scum.',
    null
  ),
  (
    'arrange-upstairs-hallway-closet',
    'Arrange Upstairs Hallway Closet',
    ':closet:',
    'Fold and organize items, remove unused items to parent review pile, and stack neatly.',
    'organization',
    'Upstairs Hallway Closet',
    'monthly',
    20,
    2,
    20,
    8,
    true,
    false,
    null,
    1,
    '{}',
    'Easy to find items.',
    null
  )
on conflict (slug) do update set
  title = excluded.title,
  emoji = excluded.emoji,
  description = excluded.description,
  category = excluded.category,
  location = excluded.location,
  frequency = excluded.frequency,
  estimated_minutes = excluded.estimated_minutes,
  difficulty = excluded.difficulty,
  base_points = excluded.base_points,
  minimum_age = excluded.minimum_age,
  requires_parent_review = excluded.requires_parent_review,
  requires_evidence = excluded.requires_evidence,
  evidence_type = excluded.evidence_type,
  undesirable_score = excluded.undesirable_score,
  dependency_slugs = excluded.dependency_slugs,
  completion_check_text = excluded.completion_check_text,
  safety_notes = excluded.safety_notes,
  active = true,
  updated_at = now();

insert into public.starter_chore_template_subtasks (
  starter_template_id,
  position,
  title
)
select sct.id, subtasks.position, subtasks.title
from public.starter_chore_templates sct
join (
  values
    ('wash-dishes', 1, 'Empty dishwasher and dish drying mat.'),
    ('wash-dishes', 2, 'Wash all dishes in sink; no visible food residue.'),
    ('wash-dishes', 3, 'Dry and return items to correct places.'),
    ('wash-dishes', 4, 'Wipe sink and surrounding counters.'),
    ('wash-dishes', 5, 'Clear and wipe dining table and chairs.'),
    ('clean-gas-cooker', 1, 'Wash and dry grates.'),
    ('clean-gas-cooker', 2, 'Clean burner caps and knobs.'),
    ('clean-gas-cooker', 3, 'Clean cooker surface and hood exterior.'),
    ('sweep-kitchen', 1, 'Sweep entire floor, including dining area.'),
    ('sweep-kitchen', 2, 'Dispose of trash and compost in outside bins.'),
    ('sweep-kitchen', 3, 'Collect recycling and arrange it in the garage.'),
    ('mop-kitchen', 1, 'Confirm sweeping is complete first.'),
    ('mop-kitchen', 2, 'Mop entire floor using configured solution or steam mop.'),
    ('mop-kitchen', 3, 'Allow floor to dry with no footprints.'),
    ('clean-living-room', 1, 'Arrange cushions and fold blankets.'),
    ('clean-living-room', 2, 'Remove trash and items that do not belong.'),
    ('clean-living-room', 3, 'Lightly dust surfaces and vacuum or sweep floor.'),
    ('clean-guest-half-bathroom', 1, 'Clean toilet seat and bowl.'),
    ('clean-guest-half-bathroom', 2, 'Wipe sink and counter.'),
    ('clean-guest-half-bathroom', 3, 'Clean mirror and replace hand towel.'),
    ('clean-guest-half-bathroom', 4, 'Sweep or mop floor.'),
    ('clean-entry-closet', 1, 'Arrange shoes neatly.'),
    ('clean-entry-closet', 2, 'Hang coats properly.'),
    ('clean-entry-closet', 3, 'Remove trash or unnecessary items.'),
    ('clean-front-entryway', 1, 'Sweep floor.'),
    ('clean-front-entryway', 2, 'Arrange shoes and mats.'),
    ('clean-front-entryway', 3, 'Wipe door handle and surfaces.'),
    ('clean-stairs', 1, 'Remove items on stairs.'),
    ('clean-stairs', 2, 'Sweep or vacuum steps.'),
    ('clean-stairs', 3, 'Wipe handrails.'),
    ('clean-upstairs-living-room', 1, 'Declutter.'),
    ('clean-upstairs-living-room', 2, 'Arrange furniture and cushions.'),
    ('clean-upstairs-living-room', 3, 'Vacuum or sweep.'),
    ('clean-laundry-room', 1, 'Remove lint and trash.'),
    ('clean-laundry-room', 2, 'Wipe machines.'),
    ('clean-laundry-room', 3, 'Sweep or mop floor and organize supplies.'),
    ('clean-bathroom-general', 1, 'Clean toilet.'),
    ('clean-bathroom-general', 2, 'Clean sink, mirror, and counters.'),
    ('clean-bathroom-general', 3, 'Sweep or mop and empty trash.'),
    ('clean-upstairs-full-bathroom', 1, 'Complete general bathroom tasks.'),
    ('clean-upstairs-full-bathroom', 2, 'Clean tub or shower walls.'),
    ('clean-upstairs-full-bathroom', 3, 'Rinse and wipe dry.'),
    ('arrange-upstairs-hallway-closet', 1, 'Fold and organize items.'),
    ('arrange-upstairs-hallway-closet', 2, 'Remove unused items to parent review pile.'),
    ('arrange-upstairs-hallway-closet', 3, 'Stack neatly.')
) as subtasks(slug, position, title)
  on subtasks.slug = sct.slug
on conflict (starter_template_id, position) do update set
  title = excluded.title;
